const classChanges = [

  /* side images */

  { time: 0, target: ".slide1", add: "show" },
  { time: 10, target: ".slide1", remove: "show" },
  { time: 10, target: ".slide2", add: "show" },
  { time: 11, target: ".slide2", remove: "show" },
  { time: 11, target: ".slide3", add: "show" },
  { time: 27, target: ".slide3", remove: "show" },
  { time: 27, target: ".slide4", add: "show" },
  { time: 31, target: ".slide4", remove: "show" },
  { time: 31, target: ".slide5", add: "show" },
  { time: 32, target: ".slide5", remove: "show" },
  { time: 32, target: ".slide6", add: "show" },
  { time: 35, target: ".slide6", remove: "show" },
  { time: 35, target: ".slide7", add: "show" },
  { time: 38, target: ".slide7", remove: "show" },
  { time: 38, target: ".slide8", add: "show" },
  { time: 39, target: ".slide8", remove: "show" },
  { time: 39, target: ".slide9", add: "show" },
  { time: 44, target: ".slide9", remove: "show" },
  { time: 44, target: ".slide10", add: "show" },
  { time: 48, target: ".slide10", remove: "show" },
  { time: 48, target: ".slide11", add: "show" },
  { time: 52, target: ".slide11", remove: "show" },
  { time: 52, target: ".slide12", add: "show" },
  { time: 73, target: ".slide12", remove: "show" },
  { time: 73, target: ".slide10", add: "show" },
  { time: 94, target: ".slide10", remove: "show" },
  { time: 94, target: ".slide14", add: "show" },
  { time: 102, target: ".slide14", remove: "show" },
  { time: 102, target: ".slide15", add: "show" },
  { time: 112, target: ".slide15", remove: "show" },
  { time: 112, target: ".slide10", add: "show" },
  { time: 125, target: ".slide10", remove: "show" },
  { time: 125, target: ".slide17", add: "show" },
  { time: 138, target: ".slide17", remove: "show" },
  { time: 138, target: ".slide10", add: "show" },
  { time: 175, target: ".slide10", remove: "show" },
  { time: 175, target: ".slide19", add: "show" },
  { time: 183, target: ".slide19", remove: "show" },
  { time: 183, target: ".slide10", add: "show" },
  { time: 213, target: ".slide10", remove: "show" },
  { time: 213, target: ".slide14", add: "show" },
  { time: 240, target: ".slide14", remove: "show" },
  { time: 240, target: ".slide22", add: "show" },
  { time: 242, target: ".slide22", remove: "show" },
  { time: 242, target: ".slide23", add: "show" },
  { time: 249, target: ".slide23", remove: "show" },
  { time: 249, target: ".slide24", add: "show" },
  { time: 276, target: ".slide24", remove: "show" },
  { time: 276, target: ".slide25", add: "show" },

  /* highlight text */

  { time: 6, target: ".t2", add: "highlight" },
  { time: 13, target: ".t2", remove: "highlight" }, 
  { time: 258, target: ".quote", add: "highlight" },
  { time: 267, target: ".quote", remove: "highlight"},
  
  { time: 20, target: ".main", add: "highlight2" },
  { time: 22, target: ".main", remove: "highlight2" },
  { time: 59, target: ".bold", add: "highlight2" },
  { time: 62, target: ".bold", remove: "highlight2" },
  { time: 277, target: ".main", add: "highlight2"},


  /* invert */

  { time: 102, target: ".main", add: "invert" },
  { time: 105, target: ".main", remove: "invert" },
  { time: 175, target: ".main", add: "invert" },
  { time: 175, target: ".main", remove: "invert" },
  { time: 274, target: ".main", add: "invert" },

  { time: 11, target: ".sidebar", add: "invert" },
  { time: 27, target: ".sidebar", remove: "invert" },  
  { time: 48, target: ".sidebar", add: "invert2" },
  { time: 52, target: ".sidebar", remove: "invert2" },  
  { time: 102, target: ".sidebar", add: "invert" },
  { time: 107, target: ".sidebar", remove: "invert" },  
  { time: 175, target: ".sidebar", add: "invert" },
  { time: 183, target: ".sidebar", remove: "invert" }, 
  { time: 276, target: ".sidebar", add: "invert"},

  { time: 102, target: ".container", add: "invert" },
  { time: 106, target: ".container", remove: "invert" },  
  { time: 175, target: ".container", add: "invert" },
  { time: 175, target: ".container", remove: "invert" }, 
  { time: 274, target: ".container", add: "invert" },
  { time: 275, target: ".container", remove: "invert" }, 

  /* hide */

  { time: 27, target: ".main", add: "hide" },
  { time: 28, target: ".main", remove: "hide" },
  { time: 272, target: ".main", add: "hide" },
  { time: 273, target: ".main", remove: "hide" },

  { time: 27, target: ".sidebar", add: "hide" },
  { time: 28, target: ".sidebar", remove: "hide" },
];
